updated scripts.

diff --git a/upload-pkgs b/upload-pkgs
--- a/upload-pkgs
+++ b/upload-pkgs
@@ -1,76 +1,56 @@
 #! /bin/sh
 
+
 server_url="https://repo.nxos.org/"
 repo=nitrux
-timestamp=$(date +%Y%m%d)
-
-
-put () { printf "\e[32m%b\e[0m\n" "$@"; }
-
-
-case "$1" in
-	--help|-h)
-		put "${0##*/}: upload packages to https://repo.nxos.org."
-		put "usage: ${0##*/} [-h|--help] <files>"
-		exit
-	;;
-esac
 
 
 test "$APTLY_USERNAME" -a "$APTLY_API_KEY" || {
-	put "please set 'APTLY_USERNAME' and 'APTLY_API_KEY' before uploading files."
-	put "ask luis for them. ;)"
-	exit 1
+    echo "please set 'APTLY_USERNAME' and 'APTLY_API_KEY' before uploading files."
+    echo "ask luis for them. ;)"
+    exit 1
 }
 
 
-for f in "$@"; do
-	test -f "$f" || {
-		echo "'$f' is not a file. aborting."
-		echo "usage: ${0##*/} [-h|--help] <files>"
-		exit 1
-	}
+for f; do
+    test -f "$f" || {
+        echo "'$f' is not a file. aborting."
+        echo "usage: upload-pkgs <files>"
+        exit 1
+    }
 done
 
 
-put "deleting remote upload directory."
-
+echo "deleting remote upload directory."
 curl -A "mozilla" \
-	-sS -u"$APTLY_USERNAME:$APTLY_API_KEY" \
-	-X DELETE \
-	"$server_url"/aptly-api/files/upload-tmp
+    -X DELETE \
+    -sS -u"$APTLY_USERNAME:$APTLY_API_KEY" \
+    "$server_url"/aptly-api/files/upload-tmp
 
 
-put "uploading files."
+for f; do set -- "$@" -F file="@$f"; shift; done
 
-#	the loop below prepends '-F file=' to each file passed.
-#	e.g.:
-#	'a.deb b.deb c.deb' gets converted to: '-F file=a.deb -F file=b.deb -F file=c.deb'.
-
-for f in "$@"; do shift; set -- "$@" -F file="@$f"; done
-
+echo "uploading files."
 curl -A "mozilla" \
-	-sS -u"$APTLY_USERNAME:$APTLY_API_KEY" \
-	-X POST "$@" \
-	"$server_url"/aptly-api/files/upload-tmp
+    -X POST "$@" \
+    -sS -u"$APTLY_USERNAME:$APTLY_API_KEY" \
+    "$server_url"/aptly-api/files/upload-tmp
 
 
-put "adding files to '$repo'."
-
+echo "adding files to $repo."
 curl -A "mozilla" \
-	-sS -u"$APTLY_USERNAME:$APTLY_API_KEY" \
-	-X POST \
-	"$server_url"/aptly-api/repos/"$repo"/file/upload-tmp
+    -X POST \
+    -sS -u"$APTLY_USERNAME:$APTLY_API_KEY" \
+    "$server_url"/aptly-api/repos/"$repo"/file/upload-tmp
 
 
-put "updating repository."
-
+echo "updating repository."
 curl -A "mozilla" \
-	-sS -u"$APTLY_USERNAME:$APTLY_API_KEY" \
-	-X PUT \
-	-H 'Content-Type: application/json' \
-	--data '{ "SourceKind": "local" }' \
-	"$server_url"/aptly-api/publish/"$repo"/nitrux
+    -X PUT \
+    -sS -u"$APTLY_USERNAME:$APTLY_API_KEY" \
+    -H 'Content-Type: application/json' \
+    --data '{ "SourceKind": "local" }' \
+    "$server_url"/aptly-api/publish/"$repo"/nitrux
 
 
-put "done."
+echo "done."
